### ISSUE TITLE
PG::ConnectionBad: FATAL:  database "jarchive_development" does not exist

### ISSUE THREAD

**Issue by NitinJami** [sottenad/jService#19]
Hi,

I am new to rails and postgres, and I am trying to setup jService and stuck at the following error:

```
$ noglob bundle exec rake get_clues[1,4]
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activesupport-4.0.2/lib/active_support/values/time_zone.rb:282: warning: circular argument reference - now
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/associations/has_many_association.rb:76: warning: circular argument reference - reflection
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/associations/has_many_association.rb:80: warning: circular argument reference - reflection
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/associations/has_many_association.rb:84: warning: circular argument reference - reflection
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/associations/has_many_association.rb:103: warning: circular argument reference - reflection
rake aborted!
PG::ConnectionBad: FATAL:  database "jarchive_development" does not exist
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:831:in `initialize'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:831:in `new'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:831:in `connect'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:548:in `initialize'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:440:in `new_connection'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:450:in `checkout_new_connection'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:421:in `acquire_connection'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:356:in `block in checkout'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:355:in `checkout'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:546:in `retrieve_connection'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_handling.rb:79:in `retrieve_connection'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/connection_handling.rb:53:in `connection'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/model_schema.rb:208:in `columns'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/model_schema.rb:217:in `columns_hash'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/dynamic_matchers.rb:60:in `block in valid?'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/dynamic_matchers.rb:60:in `each'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/dynamic_matchers.rb:60:in `all?'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/dynamic_matchers.rb:60:in `valid?'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.0.2/lib/active_record/dynamic_matchers.rb:18:in `method_missing'
/home/ubuntu/jService-master/lib/tasks/get_latest.rake:48:in `block (3 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:237:in `block in each'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:236:in `upto'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:236:in `each'
/home/ubuntu/jService-master/lib/tasks/get_latest.rake:46:in `block (2 levels) in <top (required)>'
/home/ubuntu/jService-master/lib/tasks/get_latest.rake:28:in `each'
/home/ubuntu/jService-master/lib/tasks/get_latest.rake:28:in `block in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `load'
/home/ubuntu/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `<main>'
/home/ubuntu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => get_clues
(See full trace by running task with --trace)
```

Thank you!

**Comment by sottenad** [comment]
`database "jarchive_development" does not exist` - Looks like you need to create your "jarchive_development" in your environment
